# -*- coding: utf-8 -*-
"""Dự đoán mức độ béo phì.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h16QldXaYU1CfBd1wuUNzzghUEXrA0vW
"""

#Khai báo thư viện trong quá trình xây dựng mô hình
import pandas as pd        # Xử lý dữ liệu dạng bảng
import numpy as np         # Tính toán số học, mảng
from sklearn.preprocessing import LabelEncoder  # Mã hóa dữ liệu phân loại
from sklearn.model_selection import train_test_split  # Chia tập train/test
from sklearn.ensemble import RandomForestClassifier  # Mô hình Random Forest
from sklearn.metrics import accuracy_score, classification_report  # Đánh giá mô hình
!pip install gradio #Tải thư viện gradio
import gradio as gr   # Tạo giao diện người dùng đơn giản, trực quan
import seaborn as sns #Hỗ trợ xây dựng biểu dồ heatmap
import matplotlib.pyplot as plt #Xây dựng biểu đồ thể hiện giá trị tương quan
from datetime import datetime # In ra thời gian hiện tại
import os # In ra thư mục hiện tại của chương trình
import google.generativeai as genai #Thư viện để tích hợp AI vào dự án

#Kết nối bộ dữ liệu
file_path = '/content/ObesityDataSet_raw_and_data_sinthetic.csv'
df = pd.read_csv(file_path)
print(df.head())

#Kết nối dữ liệu bổ sung
file_path_bo_sung = '/content/du_lieu_can_bang_so_nguyen.csv'
df_bo_sung = pd.read_csv(file_path_bo_sung)
print(df_bo_sung.head())

# Khởi tạo LabelEncoder
label_encoder = LabelEncoder()

# Áp dụng Label Encoding cho các cột kiểu object
for col in df_bo_sung.select_dtypes(include='object').columns:
  df_bo_sung[col] = label_encoder.fit_transform(df_bo_sung[col])

# Làm tròn các cột số không để số thực
for col in df_bo_sung.select_dtypes(include=np.number).columns:
  df_bo_sung[col] = df_bo_sung[col].round().astype(int)

# In ra thông tin của dataframe sau khi xử lý
print(df_bo_sung.head())
print(df_bo_sung.info())

# Áp dụng Label Encoding cho các cột phân loại
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
#Kiểm tra lại bộ dữ liệu
print(df.head())
print(df.info())

# Ghép hai DataFrame lại với nhau
df = pd.concat([df, df_bo_sung], ignore_index=True)

# Kiểm tra lại bộ dữ liệu sau khi ghép
print("\nDataFrame sau khi ghép:")
print(df.head())
print(df.info())

# Tính ma trận tương quan
correlation_matrix = df.corr()

# Tạo heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Biểu đồ Heatmap thể hiện sự tương quan giữa các cột')
plt.show()

X = df.drop('NObeyesdad', axis=1)
y = df['NObeyesdad']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Kích thước tập X_train:", X_train.shape)
print("Kích thước tập X_test:", X_test.shape)
print("Kích thước tập y_train:", y_train.shape)
print("Kích thước tập y_test:", y_test.shape)

# Khởi tạo mô hình Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
# Huấn luyện mô hình trên tập huấn luyện
rf_model.fit(X_train, y_train)
# Dự đoán trên tập kiểm tra
y_pred = rf_model.predict(X_test)
# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Tạo báo cáo phân loại dạng
report_dict = classification_report(y_test, y_pred, output_dict=True)
report_df = pd.DataFrame(report_dict).transpose()
label_names = le.classes_
report_df.index = [*label_names, 'accuracy', 'macro avg', 'weighted avg']
print("Báo cáo tỉ lệ dự đoán mô hình")
print(report_df)

# Khai báo biến toàn cục để lưu trữ thông tin đầu vào
user_input_info = ""
#Load mô hình dự đoán
label_mapping = {idx: label for idx, label in enumerate(le.classes_)}
prediction_log = []
#Tạo thư mục lưu trữ thông tin người dùng
excel_path = "obesity_predictions.xlsx"
# Cấu hình Gemini
genai.configure(api_key="AIzaSyDx3KqnfCJP3z382SjaX8gPfmNxDBmkVE8")
model = genai.GenerativeModel('gemini-2.0-flash')
chat = model.start_chat(history=[])
#Các tham số đầu vào
def predict_obesity(Gender, Age, Height, Weight, family_history_with_overweight, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS):
    global user_input_info  # Sử dụng biến toàn cục
    # Kiểm tra giới tính
    if Gender not in ["Nữ", "Nam"]:
        return "❌ Vui lòng chọn giới tính."
    #Kiểm tra tuổi
    if Age < 1 or Age > 100:
        return "❌ Tuổi không hợp lệ. Vui lòng nhập từ 1 đến 100 tuổi."
    # Kiểm tra đơn vị chiều cao
    if Height > 3:
        Height = Height / 100
        warning = "⚠️ Hệ thống đã tự động chuyển chiều cao từ cm sang mét."
    elif Height < 1.3 or Height > 2.2:
        return "❌ Chiều cao không hợp lệ. Vui lòng nhập từ 1.3m đến 2.2m."
    else:
        warning = ""
    # Kiểm tra cân nặng
    if Weight < 40 or Weight > 160:
        return "❌ Cân nặng không hợp lệ (40–160kg), vui lòng kiểm tra lại."

    # Tạo DataFrame từ input
    input_data = pd.DataFrame([[Gender, Age, Height, Weight, family_history_with_overweight, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS]],
                              columns=['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS'])

    # Chuyển đổi các giá trị đầu vào
    input_data['Gender'] = input_data['Gender'].map({'Nữ': 0, 'Nam': 1})
    input_data['family_history_with_overweight'] = input_data['family_history_with_overweight'].map({'Không': 0, 'Có': 1})
    input_data['FAVC'] = input_data['FAVC'].map({'Không': 0, 'Có': 1})
    input_data['CAEC'] = input_data['CAEC'].map({'Luôn luôn': 0, 'Thỉnh thoảng': 1, 'Thường xuyên': 2, 'Không': 3})
    input_data['SMOKE'] = input_data['SMOKE'].map({'Không': 0, 'Có': 1})
    input_data['SCC'] = input_data['SCC'].map({'Không': 0, 'Có': 1})
    input_data['CALC'] = input_data['CALC'].map({'Luôn luôn': 0, 'Thỉnh thoảng': 1, 'Thường xuyên': 2, 'Không': 3})
    input_data['MTRANS'] = input_data['MTRANS'].map({'Ô tô': 0, 'Xe đạp': 1, 'Xe máy': 2, 'Phương tiện công cộng': 3, 'Đi bộ': 4})

    numerical_cols = ['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']
    for col in numerical_cols:
        input_data[col] = pd.to_numeric(input_data[col])

    prediction_encoded = rf_model.predict(input_data)[0]
    prediction_label = label_mapping.get(prediction_encoded, "Unknown")

    # Ghi các kết quả dự đoán vào danh sách
    log_entry = {
        "Thời gian": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),"Tuổi": Age,"Chiều cao": Height,"Cân nặng": Weight,"Giới tính": Gender,"Lịch sử gia đình có người thừa cân": family_history_with_overweight,"Thường xuyên ăn đồ ăn calo cao": FAVC,"Tần suất tiêu thụ rau củ": FCVC,
        "Số bữa ăn chính": NCP,
        "Tiêu thụ đồ ăn vặt giữa bữa chính": CAEC,
        "Có hút thuốc không": SMOKE,
        "Lượng nước uống": CH2O,
        "Theo dõi lượng calo": SCC,
        "Hoạt động thể chất": FAF,
        "Thời gian dùng thiết bị công nghệ": TUE,
        "Tần suất uống rượu": CALC,
        "Phương tiện di chuyển chính": MTRANS,
        "Kết quả dự đoán": prediction_label
    }
    prediction_log.append(log_entry)
    df_log = pd.DataFrame(prediction_log)
    df_log.to_excel(excel_path, index=False)

    # Cập nhật thông tin đầu vào cho chatbot
    user_input_info = f"Giới tính: {Gender}, Tuổi: {Age}, Chiều cao: {Height}, Cân nặng: {Weight}, Lịch sử gia đình có người thừa cân: {family_history_with_overweight}, Thường xuyên ăn đồ ăn calo cao: {FAVC}, Tần suất tiêu thụ rau củ: {FCVC}, Số bữa ăn chính: {NCP}, Tiêu thụ đồ ăn vặt giữa bữa chính: {CAEC}, Có hút thuốc không: {SMOKE}, Lượng nước uống: {CH2O}, Theo dõi lượng calo: {SCC}, Hoạt động thể chất: {FAF}, Thời gian dùng thiết bị công nghệ: {TUE}, Tần suất uống rượu: {CALC}, Phương tiện di chuyển chính: {MTRANS}"

    return prediction_label

def chatbot_response(user_message, history):
    # Gửi thông tin đầu vào đến chatbot
    response = chat.send_message(f"{user_input_info}. {user_message}")
    return response.text

# Giao diện dự đoán béo phì
predict_interface = gr.Interface(
    fn=predict_obesity,
    inputs=[
        gr.Radio(["Nữ", "Nam"], label="Giới tính"),
        gr.Number(label="Tuổi"),
        gr.Number(label="Chiều cao (mét)"),
        gr.Number(label="Cân nặng (kg)"),
        gr.Radio(["Có", "Không"], label="Lịch sử gia đình có người thừa cân?"),
        gr.Radio(["Có", "Không"], label="Thường xuyên ăn đồ ăn calo cao?"),
        gr.Slider(minimum=1, maximum=3, step=1, label="Tần suất tiêu thụ rau củ (1:không bao giờ, 2:đôi khi, 3:luôn luôn)"),
        gr.Slider(minimum=1, maximum=3, step=1, label="Số bữa ăn chính (1:1-2 bữa, 2:3-4 bữa, 3:>4 bữa)"),
        gr.Radio(["Không", "Thỉnh Thoảng", "Thường xuyên", "Luôn luôn"], label="Tiêu thụ đồ ăn vặt giữa bữa chính?"),
        gr.Radio(["Có", "Không"], label="Có hút thuốc không?"),
        gr.Slider(minimum=1, maximum=3, step=1, label="Lượng nước uống (1:ít, 2:vừa, 3:nhiều)"),
        gr.Radio(["Có", "Không"], label="Theo dõi lượng calo?"),
        gr.Slider(minimum=0, maximum=3, step=1, label="Hoạt động thể chất (0:không, 1:1-2 ngày, 2:3-4 ngày, 3:>4 ngày)"),
        gr.Slider(minimum=0, maximum=2, step=1, label="Thời gian dùng thiết bị công nghệ (0:0-2h, 1:3-5h, 2:>5h)"),
        gr.Radio(["Không", "Thỉnh thoảng", "thường xuyên", "Luôn luôn"], label="Tần suất uống rượu?"),
        gr.Radio(["Đi bộ", "Phương tiện công cộng", "Ô tô", "Xe máy", "Xe đạp"], label="Phương tiện di chuyển chính?"),
    ],
    outputs=gr.Label(label="Dự đoán tình trạng béo phì"),
    title="Ứng dụng Dự đoán Tình trạng Béo phì",
    description="Nhập thông tin của bạn để dự đoán tình trạng béo phì.(Hãy nhập đầy đủ thông tin để có kết quả chính xác nhất)"
)

# Giao diện chatbot Gemini
chatbot_interface = gr.ChatInterface(chatbot_response, title="Trợ lý sức khỏe Gemini")
#Tạo các tabs
tabs = gr.TabbedInterface(
    [predict_interface, chatbot_interface],
    tab_names=["Dự đoán Béo phì", "Hỏi đáp cùng AI"]
)

# Khởi chạy ứng dụng
tabs.launch(debug=True)